# Generated by Django 5.1.2 on 2024-11-03 05:09

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import migrations, models

import Games_Reviews.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('reviews', models.PositiveIntegerField(
                    validators=[MaxValueValidator(5)])),
                ('image', models.ImageField(upload_to='images/%y/%m/')),
                ('developer', models.CharField(max_length=120)),
                ('publisher', models.CharField(max_length=120)),
                ('series', models.CharField(max_length=120)),
                ('platforms', models.CharField(max_length=120)),
                ('release', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=Games_Reviews.utils.generate_api_key,
                 editable=False, unique=True, max_length=120)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
