# Generated by Django 5.1.2 on 2024-11-03 05:09

import Games_Reviews.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('reviews', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/%y/%m/')),
                ('developer', models.CharField()),
                ('publisher', models.CharField()),
                ('series', models.CharField()),
                ('platforms', models.CharField()),
                ('release', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=Games_Reviews.utils.generate_api_key, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
