# Generated by Django 5.1.2 on 2024-11-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Reviews', '0002_rename_customuser_generatekeys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatekeys',
            options={'verbose_name_plural': 'GenerateKeys'},
        ),
    ]
