# Generated by Django 5.1.2 on 2024-10-31 01:58

import Games_Reviews.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Reviews', '0003_newuser_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='key',
            field=models.CharField(default=Games_Reviews.utils.generate_api_key, editable=False),
        ),
    ]
