# Generated by Django 5.1.2 on 2024-10-31 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Reviews', '0004_alter_newuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games_Reviews.review'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games_Reviews.review'),
        ),
    ]
