# Generated by Django 5.1.2 on 2024-11-30 20:43

import Games_Reviews.models
import Games_Reviews.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Reviews', '0004_alter_review_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatekeys',
            name='key',
            field=models.CharField(default=Games_Reviews.utils.generate_api_key, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='developer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='platforms',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='review',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.PositiveIntegerField(validators=[Games_Reviews.models.validate_review_value]),
        ),
        migrations.AlterField(
            model_name='review',
            name='series',
            field=models.CharField(max_length=50),
        ),
    ]
