# Generated by Django 5.1.2 on 2024-10-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Reviews', '0005_alter_genre_review_alter_mode_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games_Reviews.review'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games_Reviews.review'),
        ),
    ]
