# Generated by Django 5.1.2 on 2024-10-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Reviews', '0006_alter_genre_review_alter_mode_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='review',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
